# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6718a596c24b36293bac69bf7962b70d7479f2174187004e9e0b7183edbe7f0fda190908591b8de07af282f62e04b588a98709e650d23c24aaf8aa2bad9d96a4

test:
  secret_key_base: f72a2413b76083228eecd545de88dc85008757ce2e4dfb278849745f1d6c25344c70577d646ef3eb203b676ed7a1a336060df3b8e126887b062cdf70fe28135e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
